apiVersion: v1
kind: Pod
metadata:
  name: debug-ubuntu
  namespace: oficina-prod
spec:
  containers:
    - name: debug-ubuntu
      image: ubuntu:latest
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 128Mi
  restartPolicy: Never
